sources:
  - name: "Vietstock"
    type: vietstock
    urls:
      - "https://vietstock.vn/830/chung-khoan/co-phieu.rss"
      - "https://vietstock.vn/1636/nhan-dinh-phan-tich/nhan-dinh-thi-truong.rss"
      - "https://vietstock.vn/737/doanh-nghiep/hoat-dong-kinh-doanh.rss"
      - "https://vietstock.vn/757/tai-chinh/ngan-hang.rss"
  - name: "Markettimes"
    type: markettimes
    urls:
      - "https://markettimes.vn/rss/trang-chu"
      - "https://markettimes.vn/rss/tieu-diem"
      - "https://markettimes.vn/rss/tai-chinh"
  - name: "Người Quan Sát"
    type: nguoiquansat
    urls:
      - "https://nguoiquansat.vn/rss/chung-khoan"
      - "https://nguoiquansat.vn/rss/chung-khoan/chuyen-dong-thi-truong"
      - "https://nguoiquansat.vn/rss/doanh-nghiep/co-hoi-dau-tu"
  - name: "VnExpress"
    type: vnexpress
    urls:
      - "https://vnexpress.net/rss/kinh-doanh.rss"
  - name: "Tin Nhanh Chứng Khoán"
    type: tnck
    urls:
      - "https://www.tinnhanhchungkhoan.vn/chung-khoan/"
  - name: "VnEconomy"
    type: vneconomy
    urls:
      - "https://vneconomy.vn/chung-khoan.htm"
      - "https://vneconomy.vn/thi-truong-chung-khoan.htm"
      - "https://vneconomy.vn/dau-tu-chung-khoan.htm"
      - "https://vneconomy.vn/tieu-diem.htm"