sources:
  - name: "VnEconomy"
    type: vneconomy
    urls:
      - "https://vneconomy.vn/chung-khoan.htm"
      - "https://vneconomy.vn/thi-truong-chung-khoan.htm"
      - "https://vneconomy.vn/dau-tu-chung-khoan.htm"
